---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: ocp-monitoring
  name: ocp-monitoring
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: openshift/monitoring
    repoURL: https://github.com/angalleg/cluster-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
