---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  # outputs: 
  #   - name: rsyslog-bastion
  #     type: syslog
  #     syslog:
  #       facility: local0
  #       rfc: RFC5424
  #       severity: informational
  #     url: 'tcp://X.X.X.X:514'   # Bastion
  pipelines:
    # - name: audit-logs
    #   inputRefs:
    #     - audit
    #   outputRefs:
    #     - rsyslog-bastion
    - name: default
      inputRefs:
        - application
        - infrastructure
        - audit
      outputRefs:
        - default

