---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  # Loki Operator
  - obc-loki-bucket-odf.yaml
  - lokistack-logging-loki.yaml

  # Cluster Logging Operator
  - clusterlogging-instance.yaml
  # - clusterlogforwarder-instance.yaml
